name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          cache: true

      - name: Show Go environment
        run: |
          go version
          go env

      - name: Verify modules are tidy (no diff)
        run: |
          make tidy-all
          # Fail if tidy/vendor changed anything
          if ! git diff --exit-code; then
            echo "go.mod/go.sum/vendor drift detected. Run 'make tidy-all' and commit changes." >&2
            exit 1
          fi

      - name: Run tests
        run: make test

      - name: Build binary
        run: make build

